### ISSUE TITLE
ESM import and builtin modules like 'console' is not accessible

### ISSUE THREAD

**Issue by yqs112358** [Bzi-Han/quickjs-cmake#4]
Execute code like `import {xxx} from xxx` or `console.log('hello')` will cause error.
It is strange and I found out about this thing just now lol. 

Is there any way to fix this problem? or this feature was deliberately designed?

**Comment by Bzi-Han** [comment]
It is a feature of quickjs. 
You can find relevant functions in `quickjs-libc.h` header file, such as `js_std_add_helpers` `js_init_module_os`.
I will update the example later.

**Comment by yqs112358** [comment]
Thanks a lot!
By the way, I found that add JS_EVAL_TYPE_MODULE to JS_Eval will make ESM can be used normally. It is enough I think

**Comment by Bzi-Han** [comment]
OK, I got it.

**Comment by yqs112358** [comment]
Sorry, but I found that to support ESM is harder than I think before.
I used `JS_EVAL_TYPE_MODULE` to execute such code below:
```js
import {testfunc} from './test.js'; 
testfunc();
```
and the engine returns the exception `ReferenceError: could not load module 'test.js'`

I used VS to debug and found that the exception was throw in quickjs.c
<img width="566" alt="image" src="https://user-images.githubusercontent.com/37969157/216929514-eb9d6e3e-8179-4580-acf6-aee228882c49.png">
then I reviewed the code `qjsc.c` and find that `JS_SetModuleLoaderFunc` is used to set his own module loader. 

So I guess that we must write a module loader just like qjsc does to load ESM modules. Have you looked into this part of the code before?

**Comment by Bzi-Han** [comment]
Oh, you're right. I reviewed the code, and it is exactly what you said.
I found the solution at [qjs.c](https://github.com/Bzi-Han/quickjs-cmake/blob/main/quickjs/qjs.c#L483).
The module loader `js_module_loader` has been exported by `quickjs-libc.h`.
Try it again.

**Comment by yqs112358** [comment]
It's great. Works well. I have PRed my test
